version: '3.1'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./tests/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - 5432:5432
