apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresdatabases.experimental.bujarmurati.com
spec:
  group: experimental.bujarmurati.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                targetSecret:
                  type: object
                  properties:
                    name:
                      type: string
                    # for example 'userName@hostName'
                    userNamePostfix:
                      type: string
                  required:
                    - name
              required:
                - name
                - targetSecret
            status:
              x-kubernetes-preserve-unknown-fields: true
              type: object

      subresources:
        status: {}

  scope: Namespaced
  names:
    plural: postgresdatabases
    singular: postgresdatabase
    kind: PostgresDatabase
    shortNames:
      - pgdb
